name: art_man
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_ping: ^1.0.0
  fluttertoast: ^3.1.0
  jalali_date: ^0.1.5
  connectivity: ^0.4.3+7
  shared_preferences: ^0.5.3+4
  flutter_uploader: ^1.0.3
  seekbar: ^0.0.2
  screen: ^0.0.5
  video_player: ^0.10.1+5
  percent_indicator: ^2.1.1
  video_thumbnail: ^0.1.5+1
  path_provider: ^1.2.0
  image: any
  path: any
  dio: ^2.1.13


  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+17
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #  plugin:
  #    androidPackage: vn.hunghd.flutter.plugins.imagecropper
  #    iosPrefix: FLT
  #    pluginClass: ImageCropperPlugin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/background.png
  - assets/images/demo.gif
  - assets/images/morabi.png
  - assets/images/anatomic.png
  - assets/images/sportplan.jpg

  - assets/images/profile.png

  - assets/images/icon.png
  - assets/images/anatomi.jpg
  - assets/images/aroundArmClose.png
  - assets/images/waist.png
  - assets/images/foodplan.jpg
  - assets/images/aroundLaver.png
  - assets/images/aroundChest.png
  - assets/images/aroundWrist.png
  - assets/images/aroundNeck.png
  - assets/images/widthComb.png
  - assets/images/aroundLeg.png
  - assets/images/leg.png
  - assets/images/tall.png
  - assets/images/fields/0.jpg
  - assets/images/fields/1.jpg
  - assets/images/fields/2.jpg
  - assets/images/muscle/0.jpg
  - assets/images/muscle/1.jpg
  - assets/images/muscle/2.jpg
  - assets/images/muscle/3.jpg
  - assets/images/muscle/4.jpg
  - assets/images/muscle/5.jpg
  - assets/images/muscle/6.jpg
  - assets/images/muscle/7.jpg
  - assets/images/muscle/8.jpg
  - assets/images/muscle/9.jpg
  - assets/images/muscle/10.jpg
  - assets/images/muscle/11.jpg
  - assets/images/muscle/12.jpg
  - assets/images/muscle/13.jpg
  - assets/images/muscle/14.jpg

  - assets/images/tools/0.jpg
  - assets/images/tools/1.jpg
  - assets/images/tools/2.jpg
  - assets/images/tools/3.jpg
  - assets/images/tools/4.jpg
  - assets/images/tools/5.jpg
  - assets/images/tools/6.jpg
  - assets/images/tools/7.jpg
  - assets/images/tools/8.jpg
  - assets/images/tools/9.jpg
  - assets/images/tools/10.jpg
  - assets/images/tools/11.jpg
  - assets/images/tools/12.jpg
  - assets/images/tools/13.jpg
  - assets/images/tools/14.jpg
  - assets/images/tools/15.jpg
  - assets/images/tools/16.jpg
  - assets/images/tools/17.jpg
  - assets/images/tools/19.jpg
  - assets/images/tools/20.jpg
  - assets/images/tools/21.jpg
  - assets/images/tools/22.jpg
  - assets/images/tools/23.jpg
  - assets/images/tools/24.jpg
  - assets/images/tools/25.jpg
  - assets/images/tools/26.jpg
  - assets/images/tools/27.jpg
  - assets/images/tools/28.jpg
  - assets/images/tools/30.jpg
  - assets/images/tools/31.jpg
  - assets/images/tools/32.jpg



  # example:
  fonts:
  - family: icone
    fonts:
    - asset: assets/fonts/icomoon.ttf
  - family: iranyekan
    fonts:
    - asset: assets/fonts/normal.ttf
    - asset: assets/fonts/thin.ttf
