name: art_man
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  flutter_uploader: ^1.0.3
  seekbar: ^0.0.2
  screen: ^0.0.5
  video_player: ^0.10.1+5
  percent_indicator: ^2.1.1
  thumbnails: ^1.0.1
  path_provider: ^1.2.0
  image: any
  path: any


  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+17
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.3
  dio: ^2.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  plugin:
#    androidPackage: vn.hunghd.flutter.plugins.imagecropper
#    iosPrefix: FLT
#    pluginClass: ImageCropperPlugin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.png
    - assets/images/demo.gif
    - assets/images/morabi.jpeg
    - assets/images/anatomic.png
    - assets/images/pic1.jpeg
    - assets/images/pic2.jpeg
    - assets/images/pic3.jpeg
    - assets/images/pic4.jpeg
    - assets/images/pic5.jpeg
    - assets/images/pic6.jpeg
    - assets/images/pic7.jpeg
    - assets/images/profile.png
    - assets/images/aaa.mp4
    - assets/images/icon.png

 
  # example:
  fonts:
     - family: icone
       fonts:
         - asset: assets/fonts/icomoon.ttf

